### ISSUE TITLE
Add more details about Project Smart Kitchen

### ISSUE THREAD

**Issue by kumarrishav** [tamarahills/kitchen#2]
It will be great if we have some insights and details about this project like roadmap, user story and other info on README.md. I tried to search, but didn't find anywhere on Mozilla Wiki.  Even some reference link or docs will be helpful.

**Comment by tamarahills** [comment]
Hi Kumar!  I'll be updating readme shortly.  Here is the wiki link:  https://wiki.mozilla.org/Connected_Devices/Projects/Smart_Kitchen  Please feel free to reach out if you have questions or are interested!  Thanks, Tamara
